# Generated by Django 3.1.7 on 2021-07-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0002_auto_20210726_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
