# Generated by Django 3.1.7 on 2021-07-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0003_review_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewablecategory',
            name='directly_reviewable',
            field=models.BooleanField(default=True),
        ),
    ]
