# Generated by Django 3.1.7 on 2021-07-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0005_auto_20210726_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewableobject',
            name='image',
            field=models.ImageField(upload_to='reviewimages'),
        ),
    ]
