# Generated by Django 3.1.7 on 2021-08-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0007_auto_20210727_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uni', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_identifier', models.CharField(max_length=40)),
                ('subject_long_name', models.CharField(max_length=200)),
                ('course_number', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=100)),
                ('professors', models.ManyToManyField(to='cureview.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='reviewableobject',
            name='relatedCourse',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cureview.course'),
        ),
    ]
