# Generated by Django 3.1.7 on 2021-08-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0008_auto_20210826_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=500),
        ),
    ]
