# Generated by Django 3.1.7 on 2021-08-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0009_auto_20210826_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewablecategory',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
