# Generated by Django 3.1.7 on 2021-08-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0010_auto_20210826_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='relatedProfessor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cureview.professor'),
        ),
    ]
