# Generated by Django 3.1.7 on 2021-08-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0012_reviewableobject_numreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_identifier',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
