# Generated by Django 3.1.7 on 2021-08-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0013_auto_20210826_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='uni',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
