# Generated by Django 3.1.7 on 2021-08-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0014_auto_20210826_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='relatedProfessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cureview.professor'),
        ),
        migrations.AlterField(
            model_name='reviewableobject',
            name='relatedCourse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cureview.course'),
        ),
    ]
