# Generated by Django 3.1.7 on 2021-08-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0015_auto_20210826_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewableobject',
            name='relatedProfessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cureview.professor'),
        ),
    ]
