# Generated by Django 3.1.7 on 2021-08-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0016_reviewableobject_relatedprofessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewableobject',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
