# Generated by Django 3.1.7 on 2021-08-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureview', '0017_auto_20210826_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=50),
        ),
    ]
